### ISSUE TITLE
Date showing incorrect format:

### ISSUE THREAD

**Issue by hawarren** [CoopersHill/finance-SPA#5]
When I navigate to **enterprise-finance-application.heroku.com**
Date does not display correctly. 

Format should be "Dec. 12, 2020",
But it says "5th 12, 2020" See screenshot.

![image_2020-12-05_153753](https://user-images.githubusercontent.com/7260137/101262903-d6a35e80-370f-11eb-9bae-8c43b2dab1ad.png)

@dariquewarren Please properly format date and submit Pull request to master, to be released Sunday evening.

@dariquewarren Please also remove or hide create transaction UI until we get it wired up.
![image](https://user-images.githubusercontent.com/7260137/101263062-c475f000-3710-11eb-9229-550c70697002.png)

**Comment by hawarren** [comment]
Test these changes on a new URL, e.g. "Test-Enterprise-Finance-Application.heroku.com". that will be our QA test environment so as not to break production.

**Comment by dariquewarren** [comment]
I'm concerned about running out of space on heroku so I'm gonna look into using their development branch situation. I can push to another branch without creating a whole new site per se.

**Comment by hawarren** [comment]
@dariquewarren  I'm not sure what you mean by "using their development branch". Can you explain further?
Would we be able to run the production site and QA test site side by side, ie in 2 separate windows at the same time?


Maybe it's worth it to create a dedicated heroku account. It would remove any issues with all of us having access, space, etc.
 @hashimwarren what do you think?

**Comment by dariquewarren** [comment]
this is a three way conversation or email chain.

what i mean is, heroku has the ability to run production and qa simultaneously.
thats a process and i believe it can be done by using github to push branches instead of the git command line.

we should all look that up to understand it

**Comment by hashimwarren** [comment]
I'm less familiar with Heroku, and more familiar with AWS, which has a very generous free tier and is very popular. 

Azure also has front-end hosting. Both AWS and Azure are more popular at companies which fits with our goals. 

Ha if, do you have a preference?

**Comment by hawarren** [comment]
Hashim, can you open an issue and migrate our hosting/deployment discussion
there?

Hanif Warren
(646) 657-9403
https://hanifwarren.com
